### ISSUE TITLE
RNAType or RNALetters? (same with DNAType/DNALetters)

### ISSUE THREAD

**Issue by rhagenson** [pony-bio/pony-bio#10]
Perhaps an unnecessary concern, but is there any harm is changing the name from `RNAType` and `DNAType` to `RNALetters` and `DNALetters`? The purpose of bike shedding this is that having "Type" in the name makes reference to the type system rather than keeping the naming within the semantics of the domain. There is no `RNAType` in biology literature, but `RNALetters` is the typed equivalent of "RNA letters" or "letters of RNA" (or confusingly "RNA nucleotides" or just "RNA", neither of which I think we can accommodate).

**Comment by adri326** [comment]
No harm, these were just the names I gave them as they were `type` aliases.
