### ISSUE TITLE
Migate Gapped[T: Letter val, U: Alphabet[T] val] -> Gapped[U: Alphabet[T] val]

### ISSUE THREAD

**Issue by rhagenson** [pony-bio/pony-bio#11]
The current `Gapped` class is:

```pony
Gapped[T: Letter val, U: Alphabet[T] val]
```

However, having `T` listed twice leads me to believe we can drop the first `T` and replace it with interference from the second `T` in `Alphabet[T] val` to become `Gapped[U: Alphabet[T] val]`

**Comment by adri326** [comment]
Sadly, the definition of T has, afaik, to be explicit. With `Gapped[U: Alphabet[T] val]`, the following error is triggered:

```
Error:
/home/shadryx/Programs/pony/pony-bio/bio/alphabet/gap.pony:3:27:
class Gapped[U: (Alphabet[T] val & Complement[T] val)] is (Alphabet[(T | GapType)] & Complement[(T | GapType)])
                          ^
  can't find definition of 'T'
```

**Comment by rhagenson** [comment]
That seems like it should not be. Will you inquire about this in Zulip to
see if we are missing something or if this is a current limit of the
compiler? I will join the conversation later today (away from my computer
to, funny enough, have coffee with the two folks that introduced me to
Bioinformatics).

**Comment by rhagenson** [comment]
[Link to the thread on Zulip discussing this point.](https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help/topic/implicit.20generic.20argument)

**Comment by rhagenson** [comment]
The conclusion of the Zulip thread on this was, in brief, that although there could be such a system that infers `Alphabet[T]` to be equal to `Alphabet[T: Letter val]` based on the definition of Alphabet as `Alphabet[L: Letter val]` (implicitly giving `T` a type of `Letter val`) this is not the system Pony currently has and would take someone setting aside a substantial amount of time and effort to add this inference.

With this in mind, I am closing this issue as it is not fixable with the current state of Pony.
