### ISSUE TITLE
Letter can be > 1 in length

### ISSUE THREAD

**Issue by rhagenson** [pony-bio/pony-bio#7]
Currently, `Letter` implements a `oneletter(...)` method, however it is possible for a "letter" in an alphabet to be more than one letter in length (I know, mangled terms in Bioinformatics is great), such as in the case of a `ThreeLetterProtein` alphabet (not implemented), or a `Kmer` alphabet (not implemented). The Alphabet trait should be generic enough to support non-one length letters as-is, but the names of methods will need to change to reduce confusion. My initial recommendation is `code(...)` corresponding to the codified element.

Anybody see issue with using `code(...)` rather than `oneletter(...)`?

**Comment by adri326** [comment]
`code(...)` is a more appropriate name, `oneletter` is quite restrictive and means making assumptions about the nature of a sequence string.
